version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: vk_search_postgres
    environment:
      POSTGRES_USER: vk_user
      POSTGRES_PASSWORD: vk_password
      POSTGRES_DB: vk_search
    ports:
      - "5445:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
