services:
  postgres_db:
    image: postgres:16
    container_name: vk_search_postgres
    environment:
      POSTGRES_USER: vk_user
      POSTGRES_PASSWORD: vk_password
      POSTGRES_DB: vk_search
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: vk_search_opensearch
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "N7x!pQ4z@L9m#R2t"
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    restart: unless-stopped

  data_bootstrap:
    build:
      context: .
      dockerfile: parser/Dockerfile
    container_name: vk_search_data_bootstrap
    depends_on:
      - postgres_db
      - opensearch
    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: vk_search
      POSTGRES_USER: vk_user
      POSTGRES_PASSWORD: vk_password
      OPENSEARCH_URL: http://opensearch:9200
      OPENSEARCH_INDEX: vk_chunks
    command: ["bash", "scripts/bootstrap_seed.sh"]
    restart: "no"

volumes:
  postgres_data:
  opensearch_data: